### ISSUE TITLE
Typos in Data

### ISSUE THREAD

**Issue by KinfThaDerp** [vexed-owl/cobbled-bounties#1]
Hello! sorry as i dont really know how to write github issues

Issue : Typos in the Data for Cobbled Bounties, console spams warnings every X ticks, insane clutter
Screenshot:
![image](https://github.com/user-attachments/assets/df134979-4445-473a-822a-2bb3a6d29538)
The entire server console gets spammed by warnings

Solution: 
'minecraft:apricorn_planks' and 'minecraft:apricorn_log' use 'cobblemon:' in arborist_cm_objs
change 'cobblemon:leek_and_potato_soup' to 'cobblemon:leek_and_potato_stew' in cook_cm_objs
because apparently its a stew? i dont even know what the difference between the two is?
remove the 's' typo  'cobblemon:siapapa_berry' in arborist_cm_rews

i dont know why im even typing the solution since you'll know either way, guess im just tired at 2:20 am 

Anyway, that's it! Have a good one

**Comment by vexedowl** [comment]
Thanks for the catch! I didn't mean to miss those. I'll fix that right fast and release a fix.

**Comment by vexedowl** [comment]
Fixed! Thanks so much for catching those!
